### ISSUE TITLE
How to uninstall google apps using debloater given.

### ISSUE THREAD

**Issue by shaswat8584** [nikgapps/config#2645] opened 2022-01-19 12:32 UTC
Please give a example config file to show how to uninstall google apps.

**Comment by shaswat8584** [comment] 2022-01-19 12:43
# set to uninstall if you want to uninstall any google app, also set the value of google app below to -1
mode=uninstall
I did set this to uninstall.

**Comment by shaswat8584** [comment] 2022-01-19 12:44
set to uninstall if you want to uninstall any google app, also set the value of google app below to -1
mode=uninstall
I did set this to uninstall. And also added -1 to the packages

**Comment by shaswat8584** [comment] 2022-01-21 05:30
Anyone please help?

**Comment by dipender98** [comment] 2022-01-21 10:41
https://www.youtube.com/watch?v=jZWR9Wz7hMk

**Comment by nikhilmenghani** [comment] 2022-02-03 01:50
@shaswat8584 is your issue resolved?

**Comment by shaswat8584** [comment] 2022-02-03 03:24
@nikhilmenghani , No, I am asking how to use the debloater given to remove gapps.

**Comment by nikhilmenghani** [comment] 2022-02-03 18:11
> @nikhilmenghani , No, I am asking how to use the debloater given to remove gapps.

here is the telegram [link](https://t.me/NikGappsGroup/157968) to a tutorial on how to debloat any google app.

**Comment by nikhilmenghani** [comment] 2022-02-09 05:13
@shaswat8584 close the issue if your issue is resolved

**Comment by nikhilmenghani** [comment] 2022-02-19 17:32
Closing since no activity, assuming the issue is resolved.

**Closed by nikhilmenghani** 2022-02-19 17:32 UTC
