### ISSUE TITLE
Some more Queries that are misisng in FAQs

### ISSUE THREAD

**Issue by pixincreate** [nikgapps/config#2763] opened 2022-02-03 07:13 UTC
- GMS and playstore need not have phone and activity recognition permissions in order to work and these permissions cannot be removed at all! Kindly make it removable.
- Why dirty flashing GBoard is illegal here?
- If I remove all the scripts that start with "50-" except for `GBoard` in `/system/addon.d`, then Dirty Flash ROM(change slot if A/B device after flashing ROM) and NikGApps over it from custom recovery like TWRP, would that be feasible? (Results in Bootloop?)

**Comment by nikhilmenghani** [comment] 2022-02-03 17:57
> * GMS and playstore need not have phone and activity recognition permissions in order to work and these permissions cannot be removed at all! Kindly make it removable.
all the default permissions are denyable from gapps end.
if you check [this](https://gitlab.com/nikgapps/12/-/blob/main/Core/ExtraFiles/___etc___default-permissions/nikgapps-permissions.xml#L19) link out, the fixed attribute is what defines the forcing property of any default permission (from gapps end). We don't force enable any permission, the rom during it's first boot determines which permission should be applied on boot.
Also, I am able to deny phone permissions on LOS 19 on violet with NikGapps core. Activity is undenyable at the moment (I will check that out)
did you observe this behavior on NikGapps core?
> * Why dirty flashing GBoard is illegal here?
Some of the roms causes crash when 'Preferences' option is selected in gboard settings if Gboard is dirty flashed. Until the root cause is figured out, we're making sure GBoard is only flashable when we're clean flashing the Rom. Other apps that has similar problem are Android Auto and Google Clock. 
> * If I remove all the scripts that start with "50-" except for `GBoard` in `/system/addon.d`, then Dirty Flash ROM(change slot if A/B device after flashing ROM) and NikGApps over it from custom recovery like TWRP, would that be feasible? (Results in Bootloop?)

if you remove everything except 50-Gboard.sh, that would result into removal of all the google apps upon dirty flashing of Rom except GBoard. NikGapps is configured to keep all the packages independent, thus you should not face any bootloop. However, addon scripts are yet to be tested on A/B device with recent modifications on addon scripts so I cannot confirm if GBoard with survive dirty flashing. 
Dirty flashing Gboard addon should work in that case as once you clean flash GBoard through NikGapps addon, you can dirty flash them again.

**Comment by pixincreate** [comment] 2022-02-04 10:50
> if you check this link out,

I was looking at it yesterday in the module, we can edit that manually AFAIK, however, if we remove privilege stuffs from [this](https://gitlab.com/nikgapps/12/-/blob/main/Core/ExtraFiles/___etc___default-permissions/nikgapps-permissions.xml#L19), then I believe we can control GMS permissions.

> did you observe this behavior on NikGapps core?

I'm on LOS 18.1 Official for DRG, I couldn't remove Phone and Activity permissions at any cost as they're greyed out!  
No, I didn't try NikGApps core, however, my `minima config` always had `Core`(calendar sync excluded) and `Gboard`.

> if you remove everything except 50-Gboard.sh, that would result into removal of all the google apps upon dirty flashing of Rom except GBoard.

Based on my observation, what I found was that, dirty flashing LOS via TWRP restores everything that we've modified and leaves with ROM itself. Meaning, even if we don't remove `50-` folders, it'll be removed automatically along with root access, kernel and custom recovery.

>  I cannot confirm if GBoard with survive dirty flashing.

It doesn't survive. NikGApps itself doesn't survive unless we've recoveries something like OrangeFox is installed. NikGApps was only able to survive the update only when done through the OTA updater app.

> thus you should not face any bootloop

I, removed `50-` files, and dirty flashed the same ROM, which gets installed to the other slot, I switched to it, reboot to recovery, lost TWRP, so had to boot it again and flashed GApps minima, followed by TWRP and custom kernel(as usual), then rebooted to bootloader to boot magisk img, pushed me to recovery again, I then tried to boot to device w/o booting magisk, again pushed me to recovery, which finally lead me to clean install.

**Comment by nikhilmenghani** [comment] 2022-02-09 05:12
> I was looking at it yesterday in the module, we can edit that manually AFAIK, however, if we remove privilege stuffs from [this](https://gitlab.com/nikgapps/12/-/blob/main/Core/ExtraFiles/___etc___default-permissions/nikgapps-permissions.xml#L19), then I believe we can control GMS permissions.

I will test that before next stable release (removing the applied permissions to gms and playstore)

> I'm on LOS 18.1 Official for DRG, I couldn't remove Phone and Activity permissions at any cost as they're greyed out! No, I didn't try NikGApps core, however, my `minima config` always had `Core`(calendar sync excluded) and `Gboard`.

I tested on LOS 19.1 and I was able to remove Phone, activity was disabled. 

> Based on my observation, what I found was that, dirty flashing LOS via TWRP restores everything that we've modified and leaves with ROM itself. Meaning, even if we don't remove `50-` folders, it'll be removed automatically along with root access, kernel and custom recovery.

That is weird, which device do you have? 

> It doesn't survive. NikGApps itself doesn't survive unless we've recoveries something like OrangeFox is installed. NikGApps was only able to survive the update only when done through the OTA updater app.
I, removed `50-` files, and dirty flashed the same ROM, which gets installed to the other slot, I switched to it, reboot to recovery, lost TWRP, so had to boot it again and flashed GApps minima, followed by TWRP and custom kernel(as usual), then rebooted to bootloader to boot magisk img, pushed me to recovery again, I then tried to boot to device w/o booting magisk, again pushed me to recovery, which finally lead me to clean install.

why not just install twrp before rebooting to recovery? you won't lose twrp then, will save you the step to fastboot twrp again.
just try this

Flash Rom
Flash TWRP
Reboot to recovery
Flash Gapps
Flash Magisk
Reboot

**Comment by pixincreate** [comment] 2022-02-09 05:22
> I will test that before next stable release (removing the applied permissions to gms and playstore)

Sure, waiting for the upcoming release.

> I tested on LOS 19.1 and I was able to remove Phone, activity was disabled.

This feels weird to me, I tried flashing `NikGApps core` along with `GBoard` and `Flipendo` the other day and get that Phone and Activity removed. So, I reverted back to my own configuration `PiX-GApps-Minima` as I found it have no difference.

 > That is weird, which device do you have?

I use Nokia 6.1 Plus(DRG) as my daily driver running LOS 18.1 Official that is A/B supported.

> why not just install twrp before rebooting to recovery? you won't lose twrp then, will save you the step to fastboot twrp again.
just try this

I'd tried this before, it didn't persist TWRP, instead forced to LOS recovery. May be I'd made a mistake at that time, will try next time. :D

**Comment by nikhilmenghani** [comment] 2022-02-14 19:12
Yes, that is Rom specific.

**Comment by nikhilmenghani** [comment] 2022-02-22 06:09
@pixincreate gms_optimization is made configurable with 22nd Feb release (https://github.com/nikgapps/build/commit/bce42bbb04cb63359ca6b767a0dfa81962367061). Is there any other issue you need to discuss or I can close the issue?

**Comment by nikhilmenghani** [comment] 2022-03-05 21:22
Sandboxing can only be done at Rom side by following this link https://protonaosp.org/gapps#compatibility-layer

Flipendo will be fixed soon, I know the fix, it just needs to be implemented.

**Comment by pixincreate** [comment] 2022-03-06 11:25
> Sandboxing can only be done at Rom side by following this link https://protonaosp.org/gapps#compatibility-layer

Thank you for pointing this as a reference. I'll check it out.


Mary I know if there's anything possible to restrict GMS privileges that it asks for? Atleast permissions?

**Comment by nikhilmenghani** [comment] 2022-07-06 01:07
@pixincreate Not from gapps side!

**Comment by pixincreate** [comment] 2022-07-06 02:06
> May I know if there's anything possible to restrict GMS privileges that it asks for? Atleast permissions?

I specifically asked about Physical Activity permission here that cannot be removed.

**Comment by pixincreate** [comment] 2022-07-07 01:32
I just checked the same again, Physical Activity permission "is needed by the app to operate" is the message that message I'm getting and option has been greyed out

**Comment by nikhilmenghani** [comment] 2022-07-09 04:49
I think, in that case if we somehow disable it, the app may not work properly. It would be best to leave it that way.

**Comment by pixincreate** [comment] 2022-07-09 10:24
But I don't think it will cause problems in any way. Because, previously, Phone permission for GMS used to be the same, after some patches you made the permission removable and I use GMS with all the permissions removed and it never caused any issues so far.

However, Physical activity permission for GMS is only used for tracking the physical activity as the name itself states. Like, it detects movement when driving and stuff. It does nothing other than that.

**Closed** 2023-12-09 10:13 UTC
