### ISSUE TITLE
Elite Request: Creation of elite/13/Sinister/

### ISSUE THREAD

**Issue by vivekvijayan20** [nikgapps/config#7871] opened 2023-08-01 07:04 UTC
Hi, my name is Vivek. I am using custom ROMs for OP9 Pro. I've been using NIkGapps for a while now and I admire the work of Nikhil.

I've contributed as donation on Paypal and Patreon

**Comment by nikgapps** [comment] 2023-08-01 13:38
@vivekvijayan20 Thank you for the donation, you now have access to Sinister folder and will be receiving your first elite build as soon as you send a pull request.

The process is same as User builds, fork the config repository, upload your config file in elite/13/Sinister folder and send a pull request.

**Comment by vivekvijayan20** [comment] 2023-08-02 05:34
I send a pull request today but couldn't find the build on sourceforge

**Comment by vivekvijayan20** [comment] 2023-08-02 12:36
Every time I send a pull request it's getting merged but the build cannot be found on my folder on elite releases. Can you tell me why?

**Comment by nikgapps** [comment] 2023-08-02 13:44
I'm not sure if you're on telegram but [this](https://t.me/NikGapps/282) is why it is happening. 

I've already raised a ticket with Sourceforge.net [here](https://sourceforge.net/p/forge/site-support/24856/), the issue is on their side.

We already waited for 5 days and the issue still persists, so until sourceforge fixes it, we're actively working on alternate file hosting solution to this upload problem.

**Comment by nikgapps** [comment] 2023-08-06 16:43
Closing as the setup is complete

**Comment by nikhilmenghani** [comment] 2024-04-20 17:59
@vivekvijayan20 which android version nikgapps elites build are you using? android 13 or 14?

**Comment by nikhilmenghani** [comment] 2024-07-03 00:42
@vivekvijayan20 in preparation of android 15, I am deleting elite config for android 13, let me know if you still need it.

**Closed by nikhilmenghani** 2024-07-03 00:42 UTC
