### ISSUE TITLE
Sri_Gapps.config

### ISSUE THREAD

**Issue by Sribalaji7** [nikgapps/config#2355] opened 2021-12-07 14:17 UTC
The Google wallpaper related stuffs  are not showing after installing the gapps . . .
For Android 10
Config File - Sri_Gapps.config
Pull Request Number - #2354
Link For My Build - https://sourceforge.net/projects/nikgapps/files/Config-Releases/NikGapps-Q/07-Dec-2021/NikGapps-Sri_Gapps-arm64-10-20211207-signed.zip/download

**Comment by nikhilmenghani** [comment] 2021-12-27 04:22
The issue is now fixed, you can try building the gapps now. It'll work.

**Closed by nikhilmenghani** 2021-12-27 04:22 UTC
